# netlify.toml

[dev]
  # Port for the development server
  port = 8888
  # Command to run the local development server
  command = "npm start"

[functions]
  # Directory where Netlify functions are stored
  directory = "netlify/functions"

[[redirects]]
  # Redirect all requests to the index.html for single-page applications (SPA)
  from = "/*"
  to = "/index.html"
  status = 200
